[package]
name = "cs2-faceit-pipeline"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.48", features = ["derive"] }
thirtyfour = "0.36.1"
tokio = { version = "1.43.0", features = ["rt-multi-thread"] }
async-std = "1.13.0"
