name: Deploy Demo Lens to Azure

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_CONTAINER_REGISTRY: demolensacr1751549179
  CONTAINER_NAME: demo-lens-container
  RESOURCE_GROUP: demo-lens-rg
  IMAGE_NAME: demo-lens

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Login to Azure Container Registry
      run: az acr login --name ${{ env.AZURE_CONTAINER_REGISTRY }}
    
    - name: Build and push Docker image
      run: |
        docker build --platform linux/amd64 -t ${{ env.IMAGE_NAME }}:latest .
        docker tag ${{ env.IMAGE_NAME }}:latest ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}
        docker tag ${{ env.IMAGE_NAME }}:latest ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.IMAGE_NAME }}:latest
        docker push ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}
        docker push ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.IMAGE_NAME }}:latest
    
    - name: Restart Azure Container Instance
      run: |
        az container restart --name ${{ env.CONTAINER_NAME }} --resource-group ${{ env.RESOURCE_GROUP }}
    
    - name: Get container URL
      run: |
        FQDN=$(az container show --name ${{ env.CONTAINER_NAME }} --resource-group ${{ env.RESOURCE_GROUP }} --query ipAddress.fqdn --output tsv)
        echo "🚀 Demo Lens deployed: http://$FQDN"